apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: sundeepcharan/ticket-tickets
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_DB_URI
              value: mongodb://tickets-mongo-srv:27017/tickets
            - name: NATS_CONNECTION_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: eventticket
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
# ClusterIP service
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv-clusterip
spec:
  type: ClusterIP
  selector:
    app: tickets
  ports:
    - port: 9997
      targetPort: 9997
      name: tickets-port
      protocol: TCP
