apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: sundeepcharan/ticket-orders
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_DB_URI
              value: mongodb://orders-mongo-srv:27017/orders
            - name: NATS_CONNECTION_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: eventticket
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
# ClusterIP service
apiVersion: v1
kind: Service
metadata:
  name: orders-srv-clusterip
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - port: 9996
      targetPort: 9996
      name: orders-port
      protocol: TCP
